on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_gcc:
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        revision: [master, d82bb518fa372cc30cc3352e0a124d0bd6deb36f, 008b80e42eb7cb55c6a2ef55728241b8733dfd17, af3fc0306948f5b6abecad8453938c5bedb976fc]
        #latest: [d7e9ae4fa94afd5517536b4dfc7d6be0b3e8c2c3]
    steps:
      - name: cleanup disk space
        # - run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
        run: df -h && sudo apt purge -y azure-cli google-cloud-cli microsoft-edge-stable dotnet-* temurin-* google-chrome-stable llvm-* firefox powershell && sudo rm -rf /opt/* && docker system prune -af && sudo rm -rf /usr/local/lib/android /usr/local/.ghcup && df -h
      - name: checkout
        uses: actions/checkout@v3
      - run: ./build_gcc.sh ${{ matrix.revision }} docker.io/pbolinaro/gcc-ci:${{ matrix.revision }}
      - run: podman login docker.io -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: podman push docker.io/pbolinaro/gcc-ci:${{ matrix.revision }}
