on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_gcc:
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        revision: [master, cd794c3961017703a4d2ca0e854ea23b3d4b6373, 90c9403f89d3c55512ae83dd20e2023c2e4430f4, 2c92551405bc8616f456e5cbc696ab0292c7ff00, a857ec6aada08d8c334c389c7b682198d749b6c9, e4f0eb725d836ef0eec780cbb9e7be0d31c6fe8b, 203efd5097b86a1eb0e41ca1a6be357721d5f14d, f37c55c14bc1176ef9a15fe584fb6d1bf2e6162f, 725fb3595622a4ad8cd078a42fab1c395cbf90cb, 65e41f4fbfc539c5cc429c684176f8ea39f4b8f2]
        #latest: [96e1978b213482fc4c25693b91ae2ead481af620]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: ./build_gcc.sh ${{ matrix.revision }} docker.io/pbolinaro/gcc-ci:${{ matrix.revision }}
      - run: podman login docker.io -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: podman push docker.io/pbolinaro/gcc-ci:${{ matrix.revision }}
