on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_gcc:
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        revision: [master, 33a3f85ee4b5bc562a84c6896294278e0a5ab160, da730b29f10fb48d5ed812535768c69ff7d74248, 063564ecbfc618cd019f86216a0224e144effae1, 5445ff4a51fcee4d281f79b5f54b349290d0327d, 819bc4f6700847068883eb862dfaed11f30db80b, e1fde9de3ffa0afc804beca654a7540405de54f7, 5fdb150cd4bf8f2da335e3f5c3a17aafcbc66dbe, 7362543f00c9d3359d9377b800080fb421414ee5, b7e4a4c626eeeb32c291d5bbbaa148c5081b6bfd]
        #latest: [90bc2d09b5bfcc913f79543c3b65202e7246e162]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: ./build_gcc.sh ${{ matrix.revision }} docker.io/pbolinaro/gcc-ci:${{ matrix.revision }}
      - run: podman login docker.io -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: podman push docker.io/pbolinaro/gcc-ci:${{ matrix.revision }}
