on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_gcc:
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        revision: [master, 8106b4476482f44f042ae313f003647a1d43b372, b90089402f79ef4be049001c381dd6446af437a5, b09d948e0520574d40587c086fa43ade7316d466, 23508d3dc673de88af9a43d34d723863f1edd61d, 8ce9496f0e18f2cd1a0b86d18c534bd04fbacc31, aad881afce9edba1ccb16305c2796987c6af2543, 257a2fca4f9fdf2f506b6d5a63109fb38baacce3, a3626f49d64c8b81aadae61ae4fad7d4d0f9d6b8, 41f1b570acdea71ab107998b25a5f319a31273cd]
        #latest: [3e137ec2ef7cbfb9c7129a0e4feb416ac2e960a0]
    steps:
      - name: cleanup disk space
        # - run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
        run: df -h && sudo apt purge -y azure-cli google-cloud-cli microsoft-edge-stable dotnet-* temurin-* google-chrome-stable llvm-* firefox powershell && sudo rm -rf /opt/* && docker system prune -af && sudo rm -rf /usr/local/lib/android /usr/local/.ghcup && df -h
      - name: checkout
        uses: actions/checkout@v3
      - run: ./build_gcc.sh ${{ matrix.revision }} docker.io/pbolinaro/gcc-ci:${{ matrix.revision }}
      - run: podman login docker.io -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: podman push docker.io/pbolinaro/gcc-ci:${{ matrix.revision }}
