on:
  schedule:
    - cron: '* * * * *'

jobs:
  update_revisions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: echo update revisions
      # - run: ./build_gcc.sh ${{ matrix.revision }}
