on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update_revisions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # build 10 revisions maximum per hour
      - run: ./update_revisions.yml 10
      - run: git commit -a -m 'update revisions'
      - run: git push
