on:
  schedule:
    - cron: '0 * * * *'

permissions: write-all

jobs:
  update_revisions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # build 10 revisions maximum per hour
      - run: ./update_revisions.sh 10
      - run: git config user.name "GitHub Actions Bot"
      - run: git config user.email "<>"
      - run: git commit -a -m 'update revisions'
      - run: git push
